name: Deploy

on:
  push:
    branches: 
      - main
      
jobs:
  build-test-deploy:
    runs-on: self-hosted
    
    steps:
      -name: Checkout code
      uses: actions/checkout@v2
   
    -name: Log Doc 
    uses: actions/checkout@v3
       with:
        username: ${{ secrets.DOCKER_USERNAME }} 
        password: ${{ secrets.DOCKER_PASSWORD }}
        
      -name: Build and Push Docker image 
       uses: docker/build-push-action@v2 
       with:
        context: .
        push: true
        tags: kalana48/cicd-pipeline:${{ github.sha }}
        
      -name: Deploy to EC2 instance
       uses: appleboy/ssh-action@master 
       with:
         host: ${{secrets.EC2_HOST }}
         username: ${{secrets. EC2_USERNAME}}
         key: ${{secrets.EC2_PRIVATE_KEY}}
         script: 
            docker stop webapp || true
            docker rm webapp || true
            docker pull ${{ secrets.DOCKER_USERNAME /kalana48/cicd-pipeline:${{ github.sha }} 
            docker run-d-name kalana48/cicd-pipeline -p 80:80 ${{ secrets. DOCKER_USERNAME}}/webapp:${{ github.sha }}
